---
- name: fix cloudwatch conf
  hosts: localhost
  tasks:
    - name: restore config
      lineinfile: dest=/home/engincan/flo/cloudwatchagent/config.json
                  state=absent
                  regexp='^{{ key | replace("+", "\+") }}$'
    - name: apply config
      shell: cat /home/engincan/flo/cloudwatchagent/config.json
#shell: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl  -a fetch-config -m ec2 -c  file:/opt/aws/amazon-cloudwatch-agent/bin/config.json -s
